on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

name: Run-Targets

jobs:
    Run-Temp-Logging:
        runs-on: ubuntu-latest
        steps:
            - run: docker run --rm docker.io/jaredlander/templogging:latest
